#!/bin/bash

echo "=== SOLUÇÃO DE PROBLEMAS DO SPEEDSCAN APPIMAGE ==="
echo ""
echo "🔍 DIAGNÓSTICO:"
echo "1. Verificando AppImage:"
ls -lh ~/SpeedScan-x86_64.AppImage

echo ""
echo "2. Testando execução básica:"
timeout 3s ~/SpeedScan-x86_64.AppImage --help 2>&1 || echo "✅ AppImage responde (timeout normal)"

echo ""
echo "3. Verificando ambiente gráfico:"
echo "DISPLAY: $DISPLAY"
echo "WAYLAND_DISPLAY: $WAYLAND_DISPLAY"
echo "XDG_SESSION_TYPE: $XDG_SESSION_TYPE"

echo ""
echo "🛠️ SOLUÇÕES:"
echo ""
echo "Se o AppImage não abrir, tente:"
echo ""
echo "1️⃣  MODO TERMINAL (para testar):"
echo "   ~/SpeedScan-x86_64.AppImage --help"
echo ""
echo "2️⃣  CONFIGURAR DISPLAY MANUALMENTE:"
echo "   export DISPLAY=:0"
echo "   ~/SpeedScan-x86_64.AppImage"
echo ""
echo "3️⃣  MODO DEBUG (ver erros):"
echo "   ~/SpeedScan-x86_64.AppImage --appimage-extract-and-run"
echo ""
echo "4️⃣  VERIFICAR DEPENDÊNCIAS:"
echo "   ldd ~/SpeedScan-x86_64.AppImage | grep 'not found'"
echo ""
echo "5️⃣  EXECUTAR COM LOG DETALHADO:"
echo "   ~/SpeedScan-x86_64.AppImage 2>&1 | tee speedscan.log"
echo ""
echo "6️⃣  MODO SEGURANÇA (se tiver AppArmor):"
echo "   sudo aa-complain ~/SpeedScan-x86_64.AppImage"
echo ""
echo "7️⃣  TENTAR EXTRAIR E EXECUTAR MANUALMENTE:"
echo "   ~/SpeedScan-x86_64.AppImage --appimage-extract"
echo "   cd squashfs-root"
echo "   ./AppRun"
echo ""
echo "📋 INFORMAÇÕES DO SISTEMA:"
echo "Arquitetura: $(uname -m)"
echo "Sistema: $(uname -s)"
echo "Distribuição: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '"')"
echo ""
echo "=== FIM ==="
